# Generated by Django 3.2.2 on 2021-05-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_FIRST_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
